---
title: Alie and Nate's California Wedding
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nate@kadlac.com
description: 'Welcome to our wedding site. We''ll be updating this as we continue
  to get closer to next August.

'
baseurl: 
url: http://alieplusnate.siteleaf.net
twitter_username: kadlac
github_username: nkadlac
markdown: kramdown
theme: minima
